# Generated by Django 4.2.1 on 2023-05-16 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='description',
            new_name='Title',
        ),
    ]
